### ISSUE TITLE
行情数据查询报错

### ISSUE THREAD

**Issue by wenzhe3999** [JupiterFund/trader-ctp#3]
环境：生产
实例 : trader-ctp-pentest
错误：发送查询行情数据请求成功，trader显示行情数据查询异常，客户端也报错
分析：得到的回调数据为空，orderRef 最长允许返回13位长度的数字字符串，用 parseIntger 在这里不合适。
错误日志：
``` logger
[DEBUG] 2020-09-03 14:44:32.503 [grpc-default-executor-9] QueryService - [queryDepthMarketData] 查询行情数据.
[DEBUG] 2020-09-03 14:44:32.503 [grpc-default-executor-9] CTPRequestManager - [addListener] 添加回调监听. requestID:24
[INFO ] 2020-09-03 14:44:32.503 [grpc-default-executor-9] CTPTraderApi - [reqQryDepthMarketData] 发送查询行情数据请求成功
[INFO ] 2020-09-03 14:44:32.510 [Thread-227] CTPTraderSpi - [onRspQryDepthMarketData] 查询行情数据响应成功
[WARN ] 2020-09-03 14:44:32.510 [Thread-227] QueryService - [queryDepthMarketData] 行情数据查询异常
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_265]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_265]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673) ~[?:1.8.0_265]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_265]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_265]
        at com.nodeunify.jupiter.trader.ctp.impl.CTPTraderSpi.onRspQryDepthMarketData(CTPTraderSpi.java:382) [classes!/:?]
        at com.nodeunify.jupiter.trader.ctp.impl.CTPTraderSpiAdapter.OnRspQryDepthMarketData(CTPTraderSpiAdapter.java:101) [classes!/:?]
        at ctp.thosttraderapi.thosttradeapiJNI.SwigDirector_CThostFtdcTraderSpi_OnRspQryDepthMarketData(thosttradeapiJNI.java:10088) [ctpapi-v6.3.13-all.jar!/:?]
Caused by: java.lang.NullPointerException
        at com.nodeunify.jupiter.trader.ctp.QueryService.sanitize(QueryService.java:141) ~[classes!/:?]
        at com.nodeunify.jupiter.trader.ctp.QueryService.lambda$queryDepthMarketData$10(QueryService.java:122) ~[classes!/:?]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_265]
        ... 6 more
```

具体代码：
请查看对应日志，待完善

推荐调试方法：

本地成功运行Trader-CTP
对trader进行合约查询。

**Comment by wenzhe980406** [comment]
> 环境：生产
> 实例 : trader-ctp-pentest
> 错误：发送查询行情数据请求成功，trader显示行情数据查询异常，客户端也报错
> 分析：得到的回调数据为空，orderRef 最长允许返回13位长度的数字字符串，用 parseIntger 在这里不合适。
> 错误日志：
> 
> ```
> [DEBUG] 2020-09-03 14:44:32.503 [grpc-default-executor-9] QueryService - [queryDepthMarketData] 查询行情数据.
> [DEBUG] 2020-09-03 14:44:32.503 [grpc-default-executor-9] CTPRequestManager - [addListener] 添加回调监听. requestID:24
> [INFO ] 2020-09-03 14:44:32.503 [grpc-default-executor-9] CTPTraderApi - [reqQryDepthMarketData] 发送查询行情数据请求成功
> [INFO ] 2020-09-03 14:44:32.510 [Thread-227] CTPTraderSpi - [onRspQryDepthMarketData] 查询行情数据响应成功
> [WARN ] 2020-09-03 14:44:32.510 [Thread-227] QueryService - [queryDepthMarketData] 行情数据查询异常
> java.util.concurrent.CompletionException: java.lang.NullPointerException
>         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_265]
>         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_265]
>         at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673) ~[?:1.8.0_265]
>         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_265]
>         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
>         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_265]
>         at com.nodeunify.jupiter.trader.ctp.impl.CTPTraderSpi.onRspQryDepthMarketData(CTPTraderSpi.java:382) [classes!/:?]
>         at com.nodeunify.jupiter.trader.ctp.impl.CTPTraderSpiAdapter.OnRspQryDepthMarketData(CTPTraderSpiAdapter.java:101) [classes!/:?]
>         at ctp.thosttraderapi.thosttradeapiJNI.SwigDirector_CThostFtdcTraderSpi_OnRspQryDepthMarketData(thosttradeapiJNI.java:10088) [ctpapi-v6.3.13-all.jar!/:?]
> Caused by: java.lang.NullPointerException
>         at com.nodeunify.jupiter.trader.ctp.QueryService.sanitize(QueryService.java:141) ~[classes!/:?]
>         at com.nodeunify.jupiter.trader.ctp.QueryService.lambda$queryDepthMarketData$10(QueryService.java:122) ~[classes!/:?]
>         at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_265]
>         ... 6 more
> ```
> 
> 具体代码：
> 请查看对应日志，待完善
> 
> 推荐调试方法：
> 
> 本地成功运行Trader-CTP
> 对trader进行合约查询。
